{
 "title": "Feature flags dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "If-Else based feature usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(feature_status_total{feature=\"ifelse-feature\", status=\"enabled\"}[5s]))",
     "legendFormat": "Enabled"
    },
    {
     "expr": "sum (rate(feature_status_total{feature=\"ifelse-feature\", status=\"disabled\"}[5s]))",
     "legendFormat": "Disabled"
    }
   ]
  },
  {
   "title": "Bean based feature usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(feature_status_total{feature=\"beans-feature\", status=\"enabled\"}[5s]))",
     "legendFormat": "Enabled"
    },
    {
     "expr": "sum (rate(feature_status_total{feature=\"beans-feature\", status=\"disabled\"}[5s]))",
     "legendFormat": "Disabled"
    }
   ]
  },
  {
   "title": "Variant based feature usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (variant,payload) (rate(feature_variant_total{}[5s]))",
     "legendFormat": "Variant:{{variant}} Payload:{{payload}}"
    }
   ]
  }
 ]
}